[2025-04-16T18:02:05.645+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-16T18:02:05.673+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Medium_to_Pinecone.create_pinecone_index manual__2025-04-16T18:01:45.067787+00:00 [queued]>
[2025-04-16T18:02:05.685+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Medium_to_Pinecone.create_pinecone_index manual__2025-04-16T18:01:45.067787+00:00 [queued]>
[2025-04-16T18:02:05.686+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-04-16T18:02:05.711+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): create_pinecone_index> on 2025-04-16 18:01:45.067787+00:00
[2025-04-16T18:02:05.775+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Medium_to_Pinecone', 'create_pinecone_index', 'manual__2025-04-16T18:01:45.067787+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/HW8_Pinecone.py', '--cfg-path', '/tmp/tmp3m_s7rys']
[2025-04-16T18:02:05.781+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask create_pinecone_index
[2025-04-16T18:02:05.781+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=360) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-16T18:02:05.782+0000] {standard_task_runner.py:72} INFO - Started process 384 to run task
[2025-04-16T18:02:06.125+0000] {task_command.py:467} INFO - Running <TaskInstance: Medium_to_Pinecone.create_pinecone_index manual__2025-04-16T18:01:45.067787+00:00 [running]> on host 5ae9f2aa9b17
[2025-04-16T18:02:06.649+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Medium_to_Pinecone' AIRFLOW_CTX_TASK_ID='create_pinecone_index' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T18:01:45.067787+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T18:01:45.067787+00:00'
[2025-04-16T18:02:06.659+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-16T18:02:20.970+0000] {connectionpool.py:870} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)'))': /indexes
[2025-04-16T18:02:23.811+0000] {job.py:229} INFO - Heartbeat recovered after 18.30 seconds
[2025-04-16T18:02:29.214+0000] {job.py:229} INFO - Heartbeat recovered after 18.19 seconds
[2025-04-16T18:02:37.145+0000] {logging_mixin.py:190} INFO - Pinecone index 'semantic-search-fast' created successfully
[2025-04-16T18:02:37.150+0000] {python.py:240} INFO - Done. Returned value was: semantic-search-fast
[2025-04-16T18:02:37.231+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-16T18:02:37.232+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=Medium_to_Pinecone, task_id=create_pinecone_index, run_id=manual__2025-04-16T18:01:45.067787+00:00, execution_date=20250416T180145, start_date=20250416T180205, end_date=20250416T180237
[2025-04-16T18:02:37.288+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-16T18:02:37.321+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-16T18:02:37.324+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
