[2025-03-27T18:25:05.470+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-27T18:25:05.508+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.set_stage scheduled__2025-03-27T18:20:00+00:00 [queued]>
[2025-03-27T18:25:05.527+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.set_stage scheduled__2025-03-27T18:20:00+00:00 [queued]>
[2025-03-27T18:25:05.528+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-27T18:25:06.410+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): set_stage> on 2025-03-27 18:20:00+00:00
[2025-03-27T18:25:06.420+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1221) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-27T18:25:06.422+0000] {standard_task_runner.py:72} INFO - Started process 1233 to run task
[2025-03-27T18:25:06.421+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL', 'set_stage', 'scheduled__2025-03-27T18:20:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/HW6_ETL.py', '--cfg-path', '/tmp/tmps09egfgv']
[2025-03-27T18:25:06.425+0000] {standard_task_runner.py:105} INFO - Job 35: Subtask set_stage
[2025-03-27T18:25:09.383+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL.set_stage scheduled__2025-03-27T18:20:00+00:00 [running]> on host 67dc0bf42bd4
[2025-03-27T18:25:10.469+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='set_stage' AIRFLOW_CTX_EXECUTION_DATE='2025-03-27T18:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-27T18:20:00+00:00'
[2025-03-27T18:25:10.471+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-27T18:25:10.495+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-03-27T18:25:10.527+0000] {process_utils.py:132} INFO - Sending 15 to group 1233. PIDs of all processes in the group: [1233]
[2025-03-27T18:25:10.530+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1233
[2025-03-27T18:25:10.535+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-27T18:25:10.538+0000] {local_task_job_runner.py:127} ERROR - Received SIGTERM. Terminating subprocesses
[2025-03-27T18:25:10.542+0000] {process_utils.py:132} INFO - Sending 15 to group 1233. PIDs of all processes in the group: [1233]
[2025-03-27T18:25:10.544+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1233
[2025-03-27T18:25:10.606+0000] {taskinstance.py:3092} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-03-27T18:25:10.608+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-27T18:25:10.705+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1233, status='terminated', exitcode=2, started='18:25:05') (1233) terminated with exit code 2
[2025-03-27T18:25:10.706+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 143
